# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_cadastro(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 60, 231, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonCadastroCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCadastroCadastrar.setGeometry(QtCore.QRect(350, 400, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCadastroCadastrar.setFont(font)
        self.pushButtonCadastroCadastrar.setObjectName("pushButtonCadastroCadastrar")
        self.labelCadastroNome = QtWidgets.QLabel(self.centralwidget)
        self.labelCadastroNome.setGeometry(QtCore.QRect(140, 200, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCadastroNome.setFont(font)
        self.labelCadastroNome.setObjectName("labelCadastroNome")
        self.labelCadastroEndereco = QtWidgets.QLabel(self.centralwidget)
        self.labelCadastroEndereco.setGeometry(QtCore.QRect(120, 230, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCadastroEndereco.setFont(font)
        self.labelCadastroEndereco.setObjectName("labelCadastroEndereco")
        self.labelCadastroCpf = QtWidgets.QLabel(self.centralwidget)
        self.labelCadastroCpf.setGeometry(QtCore.QRect(150, 270, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCadastroCpf.setFont(font)
        self.labelCadastroCpf.setObjectName("labelCadastroCpf")
        self.labelCadastroNascimento = QtWidgets.QLabel(self.centralwidget)
        self.labelCadastroNascimento.setGeometry(QtCore.QRect(100, 300, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCadastroNascimento.setFont(font)
        self.labelCadastroNascimento.setObjectName("labelCadastroNascimento")
        self.lineEditCadastroNome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCadastroNome.setGeometry(QtCore.QRect(200, 200, 301, 20))
        self.lineEditCadastroNome.setObjectName("lineEditCadastroNome")
        self.lineEditCadastroEndereco = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCadastroEndereco.setGeometry(QtCore.QRect(200, 230, 301, 20))
        self.lineEditCadastroEndereco.setObjectName("lineEditCadastroEndereco")
        self.lineEditCadastroCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCadastroCpf.setGeometry(QtCore.QRect(200, 270, 113, 20))
        self.lineEditCadastroCpf.setObjectName("lineEditCadastroCpf")
        self.lineEditCadastroNascimento = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCadastroNascimento.setGeometry(QtCore.QRect(200, 300, 113, 20))
        self.lineEditCadastroNascimento.setObjectName("lineEditCadastroNascimento")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cadastro"))
        self.pushButtonCadastroCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.labelCadastroNome.setText(_translate("MainWindow", "Nome"))
        self.labelCadastroEndereco.setText(_translate("MainWindow", "Endereço"))
        self.labelCadastroCpf.setText(_translate("MainWindow", "CPF"))
        self.labelCadastroNascimento.setText(_translate("MainWindow", "Nascimento"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_cadastro()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
