# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'busca.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_busca(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(568, 443)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(250, 10, 121, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelBuscaCpf = QtWidgets.QLabel(Form)
        self.labelBuscaCpf.setGeometry(QtCore.QRect(130, 120, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelBuscaCpf.setFont(font)
        self.labelBuscaCpf.setObjectName("labelBuscaCpf")
        self.lineEditBuscaCpf = QtWidgets.QLineEdit(Form)
        self.lineEditBuscaCpf.setGeometry(QtCore.QRect(180, 120, 113, 20))
        self.lineEditBuscaCpf.setObjectName("lineEditBuscaCpf")
        self.pushButtonBuscaBuscar = QtWidgets.QPushButton(Form)
        self.pushButtonBuscaBuscar.setGeometry(QtCore.QRect(330, 120, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonBuscaBuscar.setFont(font)
        self.pushButtonBuscaBuscar.setObjectName("pushButtonBuscaBuscar")
        self.labelBuscaNome = QtWidgets.QLabel(Form)
        self.labelBuscaNome.setGeometry(QtCore.QRect(120, 210, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelBuscaNome.setFont(font)
        self.labelBuscaNome.setObjectName("labelBuscaNome")
        self.lineEditBuscaNome = QtWidgets.QLineEdit(Form)
        self.lineEditBuscaNome.setGeometry(QtCore.QRect(180, 210, 241, 20))
        self.lineEditBuscaNome.setObjectName("lineEditBuscaNome")
        self.labelBuscaEndereco = QtWidgets.QLabel(Form)
        self.labelBuscaEndereco.setGeometry(QtCore.QRect(96, 250, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelBuscaEndereco.setFont(font)
        self.labelBuscaEndereco.setObjectName("labelBuscaEndereco")
        self.labelBuscaNascimento = QtWidgets.QLabel(Form)
        self.labelBuscaNascimento.setGeometry(QtCore.QRect(80, 290, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelBuscaNascimento.setFont(font)
        self.labelBuscaNascimento.setObjectName("labelBuscaNascimento")
        self.lineEditBuscaEndereco = QtWidgets.QLineEdit(Form)
        self.lineEditBuscaEndereco.setGeometry(QtCore.QRect(180, 250, 161, 20))
        self.lineEditBuscaEndereco.setObjectName("lineEditBuscaEndereco")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 290, 161, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButtonBuscaVoltar = QtWidgets.QPushButton(Form)
        self.pushButtonBuscaVoltar.setGeometry(QtCore.QRect(240, 350, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonBuscaVoltar.setFont(font)
        self.pushButtonBuscaVoltar.setObjectName("pushButtonBuscaVoltar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Busca"))
        self.labelBuscaCpf.setText(_translate("Form", "CPF"))
        self.pushButtonBuscaBuscar.setText(_translate("Form", "Buscar"))
        self.labelBuscaNome.setText(_translate("Form", "Nome"))
        self.labelBuscaEndereco.setText(_translate("Form", "Endereco"))
        self.labelBuscaNascimento.setText(_translate("Form", "Nascimento"))
        self.pushButtonBuscaVoltar.setText(_translate("Form", "Votar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Tela_busca()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
